filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
          contains:
            docker.container.image: 42-ft_transcendence-backend
          config:
            - type: filestream
              id: container-${data.docker.container.id}
              prospector.scanner.symlinks: true
              close.on_state_change.removed: false
              parsers:
                - container: ~
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              exclude_lines: ["^\\s+[\\-`('.|_]"]




setup.kibana:
  host: "localhost:5601"

output.elasticsearch:
  hosts: 'elasticsearch:9200'
