apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    access: proxy
    url: https://prometheus:9090
    basicAuth: false
    jsonData:
      tlsSkipVerify: true
      tlsCACert: /var/certs/certificate.pem
